version: '3.8'

services:
  db:
    image: mongo:latest
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == manager

  techgear_web:
    image: thanhtrong918/node-app:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/products_db
      - PORT=3000
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-southeast-1
    networks:
      - app_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  app_network:
    driver: overlay

volumes:
  mongodb_data: