version: '3.8'
services:
  web:
    image: thanhtrong918/node-app:latest # Chúng ta sẽ build cái này ở bước CI/CD
    ports:
      - "3000:3000"
    deploy:
      replicas: 3 # Chạy 3 bản sao để đảm bảo tính sẵn sàng cao
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3