[manager]
manager_node ansible_host=13.251.252.249

[worker]
worker_node ansible_host=47.130.119.76

[all:vars]
ansible_user=ubuntu
# Chỗ này trỏ tới đường dẫn file .pem bạn vừa copy ở Bước 2
ansible_ssh_private_key_file=~/vinh-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'